version: 2
jobs:
  test_with_node_4:
    docker:
      - image: circleci/node:4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
  test_with_node_6:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
  test_with_node_8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
  test_with_node_9:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test
          command: npm run test:coverage
      - run:
          name: Deploy coverage
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  test_all:
    jobs:
      - test_with_node_4
      - test_with_node_6
      - test_with_node_8
      - test_with_node_9
